<?php



    acf_add_local_field_group(array(
                                  'key' => 'group_5d2cc3f95f048',
                                  'title' => 'Options Contact',
                                  'fields' => array(
                                      array(
                                          'key' => 'field_5d2cc5c0e8264',
                                          'label' => 'Conatc Info',
                                          'name' => '',
                                          'type' => 'tab',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'placement' => 'left',
                                          'endpoint' => 0,
                                      ),
                                      array(
                                          'key' => 'field_5d2cc5cfe8265',
                                          'label' => 'Email',
                                          'name' => 'e-mail',
                                          'type' => 'text',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'placeholder' => '',
                                          'prepend' => '',
                                          'append' => '',
                                          'maxlength' => '',
                                      ),
                                      array(
                                          'key' => 'field_5d2cc5ede8266',
                                          'label' => 'Address',
                                          'name' => 'address',
                                          'type' => 'text',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'placeholder' => '',
                                          'prepend' => '',
                                          'append' => '',
                                          'maxlength' => '',
                                      ),
                                      array(
                                          'key' => 'field_5d2cc5f8e8267',
                                          'label' => 'Mobile',
                                          'name' => 'mobile',
                                          'type' => 'text',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'placeholder' => '',
                                          'prepend' => '',
                                          'append' => '',
                                          'maxlength' => '',
                                      ),
                                      array(
                                          'key' => 'field_5d2cc40e21ff3',
                                          'label' => 'Title Area',
                                          'name' => '',
                                          'type' => 'tab',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'placement' => 'left',
                                          'endpoint' => 0,
                                      ),
                                      array(
                                          'key' => 'field_5d2cc54d21ff4',
                                          'label' => 'Custom Title',
                                          'name' => 'custom_title',
                                          'type' => 'text',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'placeholder' => '',
                                          'prepend' => '',
                                          'append' => '',
                                          'maxlength' => '',
                                      ),
                                      array(
                                          'key' => 'field_5d2cc56221ff5',
                                          'label' => 'Description Header',
                                          'name' => 'subtitle',
                                          'type' => 'text',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'placeholder' => '',
                                          'prepend' => '',
                                          'append' => '',
                                          'maxlength' => '',
                                      ),
                                      array(
                                          'key' => 'field_5d2cc59a21ff6',
                                          'label' => 'Background Color',
                                          'name' => 'background_color',
                                          'type' => 'select',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'choices' => array(
                                              'dark' => 'Dark',
                                              'light' => 'Light',
                                          ),
                                          'default_value' => array(
                                              0 => 'dark',
                                          ),
                                          'allow_null' => 0,
                                          'multiple' => 0,
                                          'ui' => 0,
                                          'return_format' => 'value',
                                          'ajax' => 0,
                                          'placeholder' => '',
                                      ),
                                  ),
                                  'location' => array(
                                      array(
                                          array(
                                              'param' => 'post_template',
                                              'operator' => '==',
                                              'value' => 'page-alcy-contact.php',
                                          ),
                                      ),
                                  ),
                                  'menu_order' => 0,
                                  'position' => 'normal',
                                  'style' => 'default',
                                  'label_placement' => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen' => '',
                                  'active' => true,
                                  'description' => '',
                              ));

